Added Hwnd property to Desktop.NativeWindow
opentk/opentk pull request #1129
Opened 2020-09-09 12:44 UTC by RedImp1470

### Purpose of this PR

* Exposing the HWND to OpenTK.Windowing.Desktop.NativeWindow

### Testing status

* Locally tested in our Engine where we need the HWND for the SpcaeMouse (and furthermore TouchDevice) implementation.
  See:  [RenderCanvasGameWindow#986](https://github.com/FUSEEProjectTeam/Fusee/blob/719bc93ce10817b3244776023d316116d74af393/src/Engine/Imp/Graphics/Desktop/RenderCanvasImp.cs#L986) and  [WindowsSpaceMouseDeviceImp#L250](https://github.com/FUSEEProjectTeam/Fusee/blob/719bc93ce10817b3244776023d316116d74af393/src/Engine/Imp/Graphics/Desktop/WindowsSpaceMouseDeviceImp.cs#L250)  
* Locally tested in Qt to set the GameWindow as a child of a QtWidget.

2020-09-09 14:51 UTC, HughPH commented on src/OpenTK.Windowing.Desktop/NativeWindow.cs
> +                Hwnd = GLFW.GlfwGetWin32Window(WindowPtr);
What happens if this method is called on non-Windows platforms?

2020-09-09 14:51 UTC, HughPH commented on src/OpenTK.Windowing.Desktop/NativeWindow.cs
> +                Hwnd = GLFW.GlfwGetWin32Window(WindowPtr);
Since the call is the same in both branches of the `if` statement, should we put it outside the statement?

2020-09-09 15:18 UTC, HughPH commented
On this PR in general:

It would be cleaner to omit the functionality entirely from non-Windows builds of OpenTK, so that developers don't call the method and expect it to work, and so that it is clear at compile time that another method needs to be used. Alternatively the Hwnd property could remain, but with an ObsoleteAttribute with the error parameter set to true when built for non-Windows platforms.

Discussed in Discord having a single method which gets whatever the native window handle is, but Linux has three possible answers. That means any code written to determine the platform would need to be tested across all major Linux distributions, and some behaviour is unknown - such as which handle would be returned if the window is running in XWayland on Wayland: would we get the X11 handle or the Wayland handle? What if we tried to call one and it failed?

2020-09-10 16:07 UTC, NogginBops commented
It would be great if you added the other functions for getting native pointers.
Seems a bit weird just to include the win32 one.

2020-09-14 22:42 UTC, NogginBops requested changes
Making this a proper review.
Just adding the function for win32 pointers is weird, if you could add the rest of the native handle functions that would be great.

2020-09-14 22:47 UTC, varon commented
Thanks for this PR, @RedImp1470 . Really great to see new contributors! Hopefully you'll join us on [the Discord chat](https://discord.gg/6HqD48s) too.

Spoke with Noggin, and he's kindly going to handle linux and other the platforms, so we're good to merge.

2020-09-14 22:47 UTC, merged