Feat: Added a method that centers the NativeWindow in the monitor it currently resides
opentk/opentk pull request #1214
Opened 2020-12-10 15:06 UTC by Timber1900

### Purpose of this PR

* Added a method that centers the NativeWindow in the monitor it currently resides,
* Modified `OpenTK.OpenTK.Windowing.Desktop.NativeWindow` class

### Testing status

* I have tested this in my own projects as it is and it appears to work correctly, however I am not sure what kind of test plan could be implemented for this feature.

### Comments

*  Refer to Issue #1213 for reference and an explanation of the method

2020-12-10 15:23 UTC, NogginBops requested changes
I would rather see this function be implemented as `bool TryCenterWindow()`.
This will allow the user to define their own default behavior for when the method fails.

There also seems to be some code style stuff as well but that is not as important. I can fix those in the end.

2020-12-10 15:23 UTC, NogginBops commented on src/OpenTK.Windowing.Desktop/NativeWindow.cs
> +                Rectangle monitorRectangle = monitorInfo.ClientArea;
This seems to be causing a CI build fail.
```
NativeWindow.cs(1730,17): error CS0246: The type or namespace name 'Rectangle' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\opentk\src\OpenTK.Windowing.Desktop\OpenTK.Windowing.Desktop.csproj]
```

2020-12-10 15:50 UTC, Timber1900 commented
Rectangle is a part of the `System.Drawing` namespace, witch isn't imported on NativeWindow.cs, I imported it however i'm not sure how you would like this to be handled. 

I also changed, per your request, the method to `bool TryCenterWindow` instead of `void CenterWindow`

2020-12-10 16:09 UTC, NogginBops approved these changes
Ok this looks good.
Now we ideally want to test this on someone else's machine before merging.

I might be able to test this, but I'm pretty busy so might not get to it super fast.
I'll see in the discord if I can get anyone to test this.

2020-12-11 17:45 UTC, seanofw commented
Honestly, I'd recommend that the method be named `CenterWindow()`, not `TryCenterWindow()`, and that it return `void`; and that if it can't figure out what monitor to put the window on, it should just throw an exception.

The only cases where GLFW will return no monitors at all are where there's something badly wrong with the OS, or where your user privileges are so broken you can't access the monitor-layout information.  In every case I can see, if you have an empty Monitors collection, your window system is simply broken.  A `Try` method suggests that it's a case that'll happen often, and people should write code to handle it.  Throwing an exception suggests that it's an exceptional circumstance, and I think in this case, letting a broken OS bubble up as a program crash is the right thing to do.

I handled it with arbitrary coordinates in my original code, and someone could catch the exception and do exactly that if they wanted to.  But let's not complicate the API by _forcing_ them to.

2020-12-13 20:42 UTC, almeidx approved these changes
LGTM

2020-12-13 22:46 UTC, seanofw commented
I'd still recommend offering the resizing overload, and making the "regular" method invoke it.  Since you're already setting the size as part of the `CenterWindow()` operation, it's not hard to support, and it _will_ result in less flicker:

```c#
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public void CenterWindow()
    => CenterWindow(Size);

public void CenterWindow(Vector2i newSize)
{
    // ...most of current implementation...
    ...
                // Actually move the window.
                ClientRectangle = new Box2i(x, y, x + newSize.X, y + newSize.Y);
    ...
}
```

This is a very small change, and provides both the "simple" usage everybody wants, and the "advanced" usage that everybody probably _should_ be using instead.  (Alternatively, you could declare `Vector2i? newSize = default` and then use `new Box2i(x, y, x + (newSize ?? Size).X, y + (newSize ?? Size).Y)`, but I think the split-method form both reads cleaner and plays nicer with reflection.)

2020-12-14 22:05 UTC, varon approved these changes

2020-12-14 22:05 UTC, merged

2020-12-14 22:06 UTC, NogginBops commented
I'll do a quick follow up PR where I add the suggestion from @seanofw .