Window size limits
opentk/opentk pull request #1395
Opened 2022-02-22 16:35 UTC by toasty1307

### Added window size limits

* Added `MinimumSize` and `MaximumSize` to `NativeWindow` and `NativeWindowSettings`
* Affects Windowing.Desktop

### Testing status

* Tested both the properties in NativeWindowSettings when creating a window
* Tested changing the properties at runtime

2022-02-22 16:42 UTC, NogginBops commented
Great PR!
We should document that if you pass `-1` (`GLFW_DONT_CARE`) as one of the dimensions to say there is no minimum or maximum.

2022-02-22 16:48 UTC, toasty1307 commented
Added the documentation!

2022-02-22 17:53 UTC, NogginBops requested changes
I just have some small comments about the documentation then I think this PR is ready to merge!
Really appreciate the PR 🙂

2022-02-22 17:53 UTC, NogginBops commented on src/OpenTK.Windowing.Desktop/NativeWindow.cs
> +        /// If you set size limits and an aspect ratio that conflict, the results are undefined.
I would say `aspect ratio lock` instead of just `aspect ratio` as I think it's somewhat unclear otherwise.

2022-02-22 17:53 UTC, NogginBops commented on src/OpenTK.Windowing.Desktop/NativeWindow.cs
> +
I think we want to say that this locks the window to this aspect ratio, but otherwise I think this is fine.

2022-02-22 17:53 UTC, NogginBops commented on src/OpenTK.Windowing.Desktop/NativeWindowSettings.cs
> +        /// Gets or sets the initial aspect ratio of the window as a numerator and denominator.
It's not only the initial aspect ratio, it's locked to this aspect ratio unless you change it later.

2022-02-22 18:05 UTC, utkumaden reviewed
I'm going to leave a small note about the double call to `glfwSetWindowSizeLimits` on back to back call to `MinSize` and `MaxSize`. I would assume the functions is practically free. The alternative is having a method which would not look good.

Otherwise no problems I see.

2022-03-09 10:44 UTC, NogginBops commented
Is this still WIP? @toasty1307

2022-03-09 10:54 UTC, toasty1307 commented
I forgot about this PR, sorry, no, not WIP anymore, everything should be done(?) @NogginBops

2022-03-09 11:01 UTC, NogginBops requested changes

2022-03-09 11:01 UTC, NogginBops commented on src/OpenTK.Windowing.Desktop/NativeWindowSettings.cs
> +        public Vector2i? MinimumSize { get; set; } = new Vector2i(GLFW.DontCare, GLFW.DontCare);
These should default to `null` instead of `GLFW.DontCare`.

2022-03-09 11:01 UTC, NogginBops commented on src/OpenTK.Windowing.Desktop/NativeWindowSettings.cs
> +        public Vector2i? MaximumSize { get; set; } = new Vector2i(GLFW.DontCare, GLFW.DontCare);
This too.

2022-03-09 11:01 UTC, NogginBops commented on src/OpenTK.Windowing.Desktop/NativeWindowSettings.cs
> +        public (int numerator, int denominator)? AspectRatio { get; set; } = (GLFW.DontCare, GLFW.DontCare);
And this one too.

2022-03-09 11:01 UTC, NogginBops commented
@toasty1307 I did find a little thing that we should change before merging. I'm happy to merge after those changes :slightly_smiling_face:

2022-03-09 11:16 UTC, NogginBops commented
Great stuff!
Will merge this now.
Really appreciate the PR! :slightly_smiling_face:

2022-03-09 11:16 UTC, merged