* remove 1-to-1 mappings of System.Math in MathHelper
opentk/opentk pull request #1733
Opened 2024-08-07 00:29 UTC by BoyBaykiller

* replace quakes invsqrt with MathF.ReciprocalSqrtEstimate
* use Vecotr512 in Equals functions
* call LengthSquared instead of typing the same thing every time

### Purpose of this PR

* Description of feature/change.
* Which part of OpenTK does this affect (Math, OpenGL, Platform, Input, etc).
* Links to screenshots, design docs, user docs, etc.

### Testing status

* Explanation of what’s tested, how tested and existing or new automation tests.
* Can include manual testing by self.
* Specify test plans.
* Rarely acceptable to have no testing.

### Comments

* Any other comments to help understand the change.

2024-08-07 01:42 UTC, BoyBaykiller commented
Done

2024-08-07 13:09 UTC, NogginBops commented on src/OpenTK.Mathematics/Matrix/Matrix4d.cs
> +            Vector512<double> bRow23 = Vector512.LoadUnsafe(ref other.Row0.X);
Should be `Row2.X`

2024-08-07 13:10 UTC, NogginBops commented on src/OpenTK.Mathematics/Matrix/Matrix4d.cs
> +            Vector512<double> aRow23 = Vector512.LoadUnsafe(ref Row0.X);
Should be `Row2.X`

2024-08-08 16:44 UTC, NogginBops requested changes

2024-08-08 16:44 UTC, NogginBops commented on src/OpenTK.Mathematics/Matrix/Matrix2x4d.cs
> +            return aRow01 == bRow01;
To match the formatting of the other implementations I think we should have blank lines separating these.

2024-08-08 16:44 UTC, NogginBops commented on src/OpenTK.Mathematics/Matrix/Matrix4.cs
> +            return aRow0123 == bRow0123;
To match the formatting of the other implementations I think we should have blank lines separating these.

2024-08-08 16:44 UTC, NogginBops commented on src/OpenTK.Mathematics/Matrix/Matrix4x3.cs
> +            Vector128<float> bRow2z3 = Vector128.LoadUnsafe(ref other.Row2.Z); // Note that we ref .Z and not .X.
The comments should have their own line, we don't put them at the end of code.

2024-08-08 16:44 UTC, NogginBops commented on src/OpenTK.Mathematics/Matrix/Matrix4x3d.cs
> +            Vector512<double> aRow01xy = Vector512.LoadUnsafe(ref Row0.X);
This should be `aRow012xy`

2024-08-08 16:44 UTC, NogginBops commented on src/OpenTK.Mathematics/Matrix/Matrix4x3d.cs
> +            Vector512<double> bRow01xy = Vector512.LoadUnsafe(ref other.Row0.X);
This should be `bRow012xy`

2024-08-08 16:44 UTC, NogginBops commented on src/OpenTK.Mathematics/Vector/Vector2.cs
> +            var scale = MathF.ReciprocalSqrtEstimate((X * X) + (Y * Y));
We should remove a few `var`s while we are at it I think.

2024-08-08 20:10 UTC, BoyBaykiller commented
You can wait with your review. I'll do one more commit

2024-08-08 23:54 UTC, NogginBops approved these changes

2024-08-08 23:55 UTC, NogginBops commented
Merging.

2024-08-08 23:55 UTC, merged